#! /usr/bin/env bash

VALIDATEFORKNAME='No'
. forktoolsinit.sh

for fork in $(ps -ef | grep _harvester | grep -v grep | awk '{print $8}' | sed 's/_harvester//' | grep -v "[s]ed" | sort); do
  echo $fork
  for port in $(cat $FORKTOOLSHIDDENDIRS/.$fork/mainnet/config/config.yaml | grep "port: " | grep -v "default_full_node_port" | sed 's/\s*[a-z_]*port: //g' | sed 's/\s*[#].*//g' | sort | uniq); do
   # echo $port - for debugging
   ss -atnp 2>/dev/null | grep :$port[^0-9] | grep -v '"'$fork_ | grep -v TIME-WAIT
  done
done


