#! /bin/bash

if [ -z "$FORKTOOLSHIDDENDIRS" ];  # sets the parent directory for all the fork hidden directories if it is empty.  Defaults to $HOME.
 then
  FORKTOOLSHIDDENDIRS="$HOME"
 fi
 
# You can set the above globally for all scripts by adding the included "forktoolsenv.sh" to your /etc/profile.d directory, modified to your taste.  
# Requires sudo root permissions.  Making this permanent may require a reboot.


tail -100 $FORKTOOLSHIDDENDIRS/.$1/mainnet/log/debug.log


