#! /bin/bash

if [ -z "$FORKTOOLSBLOCKCHAINDIRS" ];  # sets the parent directory for all the fork-blockchain directories if it is empty.  Defaults to $HOME.
 then
  FORKTOOLSBLOCKCHAINDIRS="$HOME"
 fi

# You can set the above globally for all scripts by adding the included "envforktools.sh" to your /etc/profile.d directory, modified to your taste.  
# Requires sudo root permissions.  Making this permanent may require a reboot.

cd $FORKTOOLSBLOCKCHAINDIRS/$1-blockchain 
. ./activate

for port in $($1 show -c | grep "^FULL_NODE" | awk '{print $2,$3}' | sed 's/\s[0-9]*\//:/' ); do
  echo $1 "show -a" $port
done
 





