#! /usr/bin/env bash

function print_usage () {
   echo "forkver help:"
   echo
   echo "SYNOPSIS:  Prints the output of 'forkname version' for the specified fork."
   echo
   echo "PARAMETERS:"
   echo "    forkname            Required."
   echo "    -help | --help      Show this information again."
   echo
   exit 0
}

VALIDATEFORKNAME='Yes'
. ftinit.sh

cd $FORKTOOLSBLOCKCHAINDIRS/$1-blockchain 
. ./activate 
$1 version
deactivate


