#! /usr/bin/env bash

function print_usage () {
   echo "forkaddplotdirs help:"
   echo
   echo "SYNOPSIS:  Runs 'forkname plots add -d directoryname' for each entry in ftconfigs/config.forkaddplotdirs."
   echo "           Restarting the fork(s) with forkstart after running this script is recommended to ensure the new"
   echo "           directories are loaded immediately."
   echo
   echo "PARAMETERS:"
   echo "    forkname | all      Required.  Runs for the specified fork, or all forks with an active harvester process."
   echo "    -help | --help      Show this information again."
   echo
   exit 0
}   


if [[ $1 != 'all' ]]; then
  VALIDATEFORKNAME='Yes'
fi
. ftinit.sh

if [[ $3 != '' ]]; then
  echo "forkaddplotdirs:  Too many specified parameters."
  print_usage
fi

if [[ $1 == 'all' ]]; then
   . ftbuildharvesterlist.sh
else
   HARVESTERLIST=$1
fi

OLDIFS=$IFS
IFS=$'\n'
for fork in $HARVESTERLIST; do
   if [[ $1 != 'all' && $1 != $fork ]]; then
      continue
   fi
   if [[ -f $FORKTOOLSDIR/ftconfigs/config.forkaddplotdirs.$fork ]]; then
     . $FORKTOOLSDIR/ftconfigs/config.forkaddplotdirs.$fork
   else
     . $FORKTOOLSDIR/ftconfigs/config.forkaddplotdirs
   fi   
   cd $FORKTOOLSBLOCKCHAINDIRS/$fork-blockchain 
   . ./activate          
   for plotdir in $FORKADDPLOTDIRS; do
      STRIPPEDCOMMENTS=$(sed 's/#.*//' <<< "$plotdir" | awk '{$1=$1};1' )
      if [ -n "$STRIPPEDCOMMENTS" ]; then
         BUILDEXPR=$(echo "$fork plots add -d '$STRIPPEDCOMMENTS'")
         echo 'forkaddplotdirs running: ' $BUILDEXPR 
         if [[ ( ! -d "$STRIPPEDCOMMENTS" ) ]]; then
           echo -e "\e[1;31m   WARNING:  \e[0m $STRIPPEDCOMMENTS is not a mounted directory.  \e[1;31m  :WARNING \e[0m"
         fi
         echo $(eval $BUILDEXPR)
      fi
   done  
   deactivate
done
IFS=$OLDIFS
echo
