#! /usr/bin/env bash

. $FORKTOOLSDIR/ftconfigs/config.logging

if [[ $LOGFORKFIXCONFIG == 'true' ]]; then
  forkfixconfigq $* | tee -a $FORKTOOLSDIR/ftlogs/forkfixconfig.log
else
  forkfixconfigq $*
fi  
