#! /usr/bin/env bash

function print_usage () {
   echo "forklist help:"
   echo
   echo "SYNOPSIS:  Provides a count of running farmers, running harvesters, and installed forks that aren't running,"
   echo "     along with a single line list of forks in each category."
   echo
   echo "PARAMETERS:"
   echo "     -help | --help      Show this information again."
   echo
   exit 0
}

. ftinit.sh

. ftbuildrunlists.sh
echo "Farmer count:" $FARMERCOUNT
echo $FARMERLIST
echo
echo "Harvester count:" $HARVESTERCOUNT
echo $HARVESTERLIST
echo
echo "Stopped count:" $STOPPEDCOUNT
echo $STOPPEDLIST
echo
