#! /usr/bin/env bash

function print_usage () {
   echo "forkcheck help:"
   echo
   echo "SYNOPSIS:   Displays important port settings per the config.yaml of all forks with a -blockchain"
   echo "    directory, then also checks the initial-config.yaml that generates the config during a fresh"
   echo "    installation.  If they are the same, that fork will display only one line and the last column"
   echo "    will display 'matched'.  If they are not the same, that fork will display two lines, one for the"
   echo "    standard ports from the initial-config.yaml and the other from the operating config.yaml in the"
   echo "    hidden directory.  Review those carefully, as at least one of the ports does not match."
   echo "            If you have a mismatch and the discrepancy is not intended, running forkupdate for the"
   echo "    fork is a quick solution as it always generates a new config from the initial-config.yaml."
   echo "            If the discrepancy is intended to resolve a port conflict, consider creating a"
   echo "    config.forkfixconfig.forkname override so that forktools can consistently apply this override"
   echo "    during forkfixconfig and forkupdate."
   echo
   echo "PARAMETERS:"
   echo "     -help | --help      Show this information again."
   echo
   exit 0
}

. ftinit.sh

cd $FORKTOOLSBLOCKCHAINDIRS
FORKLIST=$( ls -d1 *-blockchain | sed 's/-blockchain//' )

printf "FORK            VERSION         HARVESTER  HARVESTER  FARMER     FARMER     WALLET     WALLET     TIMELORD   TIMELORD   FULLNODE   FULLNODE   DAEMON     UI         Match\n"
printf "                                           RPC                   RPC                   RPC        LAUNCHER                         RPC                              Init?\n"
echo   "---------------------------------------------------------------------------------------------------------------------------------------------------------------------------"



for FORKNAME in $FORKLIST; do
   CURRENTCONFIG=$FORKTOOLSHIDDENDIRS/.$FORKNAME/mainnet/config/config.yaml
   if [[ ! -f $CURRENTCONFIG ]]; then
      continue
   fi  
   CURRENTCONFIG=$FORKTOOLSBLOCKCHAINDIRS/$FORKNAME-blockchain/$FORKNAME/util/initial-config.yaml
   if [[ ! -f $CURRENTCONFIG ]]; then
      continue
   fi  

   . $FORKTOOLSDIR/ftparseports.sh
   
   IFULLNODEPORT=$FULLNODEPORT
   IFULLNODERPCPORT=$FULLNODERPCPORT
   IFARMERPORT=$FARMERPORT
   IFARMERRPCPORT=$FARMERRPCPORT
   IHARVESTERPORT=$HARVESTERPORT
   IHARVESTERRPCPORT=$HARVESTERRPCPORT
   IWALLETPORT=$WALLETPORT
   IWALLETRPCPORT=$WALLETRPCPORT
   ITIMELORDPORT=$TIMELORDPORT
   ITIMELORDLAUNCHERPORT=$TIMELORDLAUNCHERPORT
   IDAEMONPORT=$DAEMONPORT
   IUIPORT=$UIPORT
   IUIRPCPORT=$UIRPCPORT
   
   CURRENTCONFIG=$FORKTOOLSHIDDENDIRS/.$FORKNAME/mainnet/config/config.yaml
   . $FORKTOOLSDIR/ftparseports.sh

   FORKVER=$( $FORKTOOLSDIR/fork $FORKNAME ver )
   
   MATCHSTATUS='matched'
   if [[ $HARVESTERPORT != $IHARVESTERPORT || $HARVESTERRPCPORT != $IHARVESTERRPCPORT || $FARMERPORT != $IFARMERPORT || $FARMERRPCPORT != $IFARMERRPCPORT ||  $WALLETPORT != $IWALLETPORT || $WALLETRPCPORT != $IWALLETRPCPORT || $TIMELORDLAUNCHERPORT != $ITIMELORDLAUNCHERPORT || $TIMELORDPORT != $ITIMELORDPORT || $FULLNODEPORT != $IFULLNODEPORT || $FULLNODERPCPORT != $IFULLNODERPCPORT || $DAEMONPORT != $IDAEMONPORT || $UIPORT != $IUIPORT ]]; then
      printf "%-15s %-15s %-10s %-10s %-10s %-10s %-10s %-10s %-10s %-10s %-10s %-10s %-10s %-10s initial-config.yaml\n" $FORKNAME $FORKVER $IHARVESTERPORT $IHARVESTERRPCPORT $IFARMERPORT $IFARMERRPCPORT $IWALLETPORT $IWALLETRPCPORT $ITIMELORDLAUNCHERPORT $ITIMELORDPORT $IFULLNODEPORT $IFULLNODERPCPORT $IDAEMONPORT $IUIPORT
      MATCHSTATUS='config.yaml'      
   fi
   printf "%-15s %-15s %-10s %-10s %-10s %-10s %-10s %-10s %-10s %-10s %-10s %-10s %-10s %-10s %-11s\n" $FORKNAME $FORKVER $HARVESTERPORT $HARVESTERRPCPORT $FARMERPORT $FARMERRPCPORT $WALLETPORT $WALLETRPCPORT $TIMELORDLAUNCHERPORT $TIMELORDPORT $FULLNODEPORT $FULLNODERPCPORT $DAEMONPORT $UIPORT $MATCHSTATUS
done



