#! /usr/bin/env bash

. $FORKTOOLSDIR/ftconfigs/config.logging

if [[ $LOGFORKADDPLOTDIRS == 'true' ]]; then
  forkaddplotdirsq $* | tee -a $FORKTOOLSDIR/ftlogs/forkaddplotdirs.log
else
  forkaddplotdirsq $*
fi  
