#! /usr/bin/env bash

VALIDATEFORKNAME='No'
. forktoolsinit.sh

# Stops all services for all forks with an active harvester process

. ftbuildharvesterlist.sh

for fork in $HARVESTERLIST; do
   cd $FORKTOOLSBLOCKCHAINDIRS/$fork-blockchain 
   . ./activate 
   echo "Stopping: " $fork
   $FORKTOOLSDIR/forkstopa $fork
done



