#! /usr/bin/env bash

. $FORKTOOLSDIR/ftconfigs/config.logging

if [[ $LOGFORKBENCHIPS == 'true' ]]; then
  forkbenchipsq $* | tee -a $FORKTOOLSDIR/ftlogs/forkbenchips.log
else
  forkbenchipsq $*
fi  
