#! /usr/bin/env bash

function print_usage () {
   echo "forkconfig help:"
   echo
   echo "SYNOPSIS:  Opens the specified fork's config.yaml in a text editor, gedit by"
   echo "    default.  The user can set a preferred editor in ftconfigs/config.forkconfig."  
   echo
   echo "PARAMETERS:"
   echo "    forkname            Required."
   echo "    -help | --help      Show this information again."
   echo
   exit 0
}

VALIDATEFORKNAME='Yes'
. ftinit.sh

$FORKCONFIGEDITOR $FORKTOOLSHIDDENDIRS/.$1/mainnet/config/config.yaml


