#! /usr/bin/env bash

VALIDATEFORKNAME='No'
. forktoolsinit.sh

. ftbuildharvesterlist.sh

for fork in $HARVESTERLIST; do
  echo "Scanning: $fork"
  for port in $(cat $FORKTOOLSHIDDENDIRS/.$fork/mainnet/config/config.yaml | grep "port: " | grep -v "default_full_node_port" | sed 's/\s*[a-z_]*port: //g' | sed 's/\s*[#].*//g' | sort | uniq); do
   # echo $port - for debugging
   ss -atnp 2>/dev/null | grep :$port[^0-9] | grep -v '"'$fork_ | grep -v TIME-WAIT
  done
done


